protected/controllers/SiteController.php
<?php

/**
 * Class SiteController
 */
class SiteController extends Controller
{
    public function init()
    {
        Yii::app()->theme = null;

        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class'     => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page'    => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex($r_id = null)
    {

        if ($r_id) {
            $emailInviteModel = new EmailInvite();

            if ($emailInviteModel->isExistsRequestID($r_id)) {
                $cookie                                = new CHttpCookie('e_r_id', $r_id);
                $cookie->expire                        = time() + 60 * 60 * 24 * 30;
                Yii::app()->request->cookies['e_r_id'] = $cookie;
            }
        }

        if (!empty(Yii::app()->user->data)) {

            Yii::trace(CVarDumper::dumpAsString(Yii::app()->user->data), 'vardump');

            if (!empty(Yii::app()->user->data->ConsumerGUID)) {

                $emailRequestID = (isset(Yii::app()->request->cookies['e_r_id']->value)) ?
                    Yii::app()->request->cookies['e_r_id']->value : '';

                if ($emailRequestID) {
                    $emailInviteModel = new EmailInvite();

                    if ($emailInviteModel->isExistsRequestID($emailRequestID)) {
                        $emailInviteModel->attributes = array(
                            'EmailRequestID' => $emailRequestID,
                            'FriendUserGUID' => Yii::app()->user->data->ConsumerGUID,
                            'InviteStatus'   => 'invited',
                        );

                        if ($emailInviteModel->validate()) {
                            if ($emailInviteModel->updateInviteStatus()) {
                                unset(Yii::app()->request->cookies['e_r_id']);
                            };

                        } else {

                        }
                    } else {
                        unset(Yii::app()->request->cookies['e_r_id']);
                    }
                } else {
                    unset(Yii::app()->request->cookies['e_r_id']);
                }
            }
        }

        $this->render('index');
    }

    /**
     * Рендерит страницу "Правила"
     */
    public function actionRules()
    {
        $this->render('rules');
    }

    /**
     * Рендерит страницу "Подарки"
     */
    public function actionGifts()
    {
        $this->render('gifts');
    }


    /**
     * Рендерит страницу регистрации
     */
    public function actionRegistration()
    {
        $model = new PassportRegistrationForm();

        if ($post = Yii::app()->request->getPost('PassportRegistrationForm')) {
            $model->attributes = $post;

            if ($model->validate()) {
                $model->save();
            }
        } else {
            if(!Yii::app()->user->hasFlash('RegistrationAllowed')){
                $this->redirect('http://football.bud.ua');
                Yii::app()->end();
            }
        }

        $this->render('registration/index', array('model' => $model));
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the login page
     */
    public function actionLogin()
    {
        $service = Yii::app()->request->getQuery('service');

        if (!empty($service)) {
            $authIdentity              = Yii::app()->eauth->getIdentity($service);
            $authIdentity->redirectUrl = Yii::app()->user->returnUrl;
            $authIdentity->cancelUrl   = $this->createAbsoluteUrl('site/index');

            if ($authIdentity->authenticate()) {
                $identity = new ServiceUserIdentity($authIdentity);
                // Успешный вход
                if ($identity->authenticate()) {

                    Yii::app()->user->login($identity);
                    $user = new Users();

                    // если пользователь не найден по его id
                    // редиректим на регистрацию
                    if ($userData = $user->getUser(array('FacebookUserID' => Yii::app()->user->id))) {
                        if ($userData['MValidCode'] == 1) {
                            Yii::app()->user->data = (object)$userData;

                            // Фиксируем пользователя как участника активности
                            $consumerGUID = !empty(Yii::app()->user->data->ConsumerGUID) ? Yii::app()->user->data->ConsumerGUID : null;

                            if ($consumerGUID) {
                                $params = array('ConsumerGUID' => $consumerGUID);

                                Users::setCampaignActivity($params);
                            }

                            $authIdentity->redirect();
                        } else {
                            // Редирект на регистрацию
                            $authIdentity->redirect(Yii::app()->createUrl('site/registration'));

                        }
                    } else {
                        /*
                         * если пользователя нашли по email,
                         * апдейдтим его facebookID
                         * */
                        if ($userData = $user->getUser(array('EmailAddress' => Yii::app()->user->email))) {
                            if ($userData['MValidCode'] == 1) {
                                Yii::app()->user->data = (object)$userData;

                                /*
                                 * проверяем, совпадает ли facebookID найденного пользователя с facebookID залогиненного.
                                 * Если не совпадает - апдейтим учетную запись
                                 * */
                                if (Yii::app()->user->id != $userData['FaceBookUserID']) {
                                    $regModel = new RegistrationForm();

                                    $regModel->attributes = array(
                                        'LastName'       => $userData['LastName'],
                                        'FirstName'      => $userData['FirstName'],
                                        'Patronymic'     => $userData['Patronymic'],
                                        'Birthday'       => $userData['BirthDate'],
                                        'Gender'         => $userData['GenderValue'],
                                        'CityName'       => $userData['CityName'],
                                        'Rayon'          => $userData['RayonName'],
                                        'Oblast'         => $userData['OblastName'],
                                        'operatorCode'   => substr($userData['MainMobilePhone'], 0, 5),
                                        'MobilePhone'    => substr($userData['MainMobilePhone'], 5, 7),
                                        'Email'          => $userData['EmailAddress'],
                                        'Password'       => $userData['Password'],
                                        'FaceBookUserID' => Yii::app()->user->id
                                    );

                                    $regModel->save();
                                }

                                $authIdentity->redirect();
                            } else {
                                // Редирект на регистрацию
                                $authIdentity->redirect(Yii::app()->createUrl('site/registration'));
                            }

                        } else {
                            // Редирект на регистрацию
                            $authIdentity->redirect(Yii::app()->createUrl('site/registration'));
                        }
                    }
                } else {
                    // Закрываем popup окно и перенаправляем на cancelUrl
                    $authIdentity->cancel();
                }
            }

            // Что-то пошло не так, перенаправляем на страницу входа
            $this->redirect(array('site/index'));
        }

        $model = new LoginForm;

        // collect user input data
        if ($post = Yii::app()->request->getPost('LoginForm')) {
            $model->attributes = $post;
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login()) {


                // $this->redirect('site/index');

                // Yii::app()->end();
            } else {
                Yii::app()->user->setFlash('loginError', 'error');
            }
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }


    /**
     * This is the method to rendering auth page
     */
    public function actionAuth()
    {
        $this->render('auth');
    }

    /**

protected/views/site/html/ga.php
<?php
/**
 * Шаблон с кодом Google Analytics
 * @var $this SiteController
 */
?>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-35115029-13', 'bud.ua');
    ga('send', 'pageview');
</script>

protected/views/site/html/loginBlock.php
<?php
/**
 * Шаблон блока авторизации + форма ввода логина/пароля
 * @var $this SiteController
 */
?>
<style type="text/css">
    .reminder-lnk{
        position: absolute;
        left: 130px;
        top: 0;
        color: #bd0d2a;
        font-size: 14px;
        margin-right: 15px;
        text-decoration: none;
        display: inline-block;
        vertical-align: middle;
        border-bottom: 2px solid transparent;
        margin-top: 12px;
        transition: ease-out .5s;
    }

    .reminder-lnk:hover{
        border-bottom: 2px solid #bd0d2a;
    }
</style>
<div class="login-block">
    <div class="login-form left">
        <?php
        $loginModel = new LoginForm();

        if (Yii::app()->request->isPostRequest) {
            if ($post = Yii::app()->request->getPost('LoginForm')) {
                $loginModel->attributes = $post;

                // validate user input and redirect to the previous page if valid
                if ($loginModel->validate() && $loginModel->login()) {
                    $this->redirect(Yii::app()->user->returnUrl);
                }
            }
        }
        $this->renderPartial('//site/login', array('model' => $loginModel));
        ?>
    </div>


        <!--<div class="login-btns">
            <a href="#" class="btn"
               onclick="$('#login-form').submit()">Вхід</a><?php /*echo CHtml::link('Реєстрація', Yii::app()->createUrl('site/registration'), array('class' => 'btn fb-btn', 'id'=>'top-reg-btn')) */?>
        </div>-->
</div>

protected/views/site/html/topNavigation.php
<?php
/**
 * Шаблон верхнего меню
 *
 * @var $this SiteController
 */
?>
<nav class="left">
    <?php $this->widget('zii.widgets.CMenu', array(
        'activeCssClass' => 'mitem-active',
        'items'          => array(
            array('label' => 'Головна', 'url' => array('/site/index')),
            array('label' => 'Правила', 'url' => array('/site/rules'),'template'=>'| {menu}'),
            array('label' => 'Тест', 'url' => array('/test'), 'template'=>'| {menu}'),
            array('label' => 'Подарунки', 'url' => array('/site/gifts'), 'template'=>'| {menu}'),
            array('label' => 'Запросити друга', 'url' => array('/invite'), 'template'=>'| {menu}'),
            array('label' => "Зворотній зв’язок", 'url' => array('/site/feedback'), 'template'=>'| {menu}'),
        ),
    )); ?>
</nav>
<div class="login-btns right">
    <a href="http://bud.ua" target="_blank" style="width: 180px; margin-top: 5px;">Перейти на bud.ua</a>
    <?php if (Yii::app()->user->isGuest) : ?>
        <a href="#" id="login-btn">Вхід</a>
    <?php else: ?>
        <?php if(!empty(Yii::app()->user->data->ConsumerGUID)) : ?>
            <?php echo '<span>Вітаємо, </span>' . CHtml::link(Yii::app()->user->name, Yii::app()->createUrl('/profile'), array('class' => 'profile-lnk')); ?>
        <?php endif ?>

        <?php echo CHtml::link('Вихід', array('site/logout'), array('id' => 'logout-btn')) ?>
    <?php endif ?>
</div>